version: "1"

databases:
  - name: eathiopia_db
    databaseName: eathiopia_db
    user: rodasgeberhiwet

services:
  # 1. THE BACKEND
  - type: web
    name: eathiopia-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eathiopia_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0

  # 2. THE FRONTEND
  - type: web
    name: eathiopia-frontend
    env: static
    # Removed "region" (Static sites are global)
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://eathiopia-backend.onrender.com